config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :articles
  get 'presentation', to: 'pages#presentation'
  get 'ateliers', to: 'pages#ateliers'
  get 'meubles', to: 'pages#meubles'
  get 'woodart', to: 'pages#woodart'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SebCopeauxLudiks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="bg">
    <%= render 'shared/flashes' %>
    <%= yield %>
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="https://www.facebook.com/copeauxludiks/" target="_blank"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
          <a href="#" class="top">TOP<i></i></a>
      </div>
    </div>
  </body>
</html>

app/views/pages/ateliers.html.erb
<div class="bg">

  <div class="footer">
    <div class="footer-links">
    </div>
  </div>

  <div class="card-trip mx-auto">
    <img src="https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2018/04/07/node_353848/39330516/public/2018/04/07/B9715318602Z.1_20180407192223_000%2BG0CB22QDD.1-0.jpg?itok=E3x0Y8W31523178856" />
    <div class="card-trip-infos">
      <div>
        <h2>Les ateliers</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates ullam quasi voluptatum at, eligendi vitae ratione asperiores quo, possimus, enim quibusdam. Eligendi hic quae laborum totam molestiae. Voluptate, quis facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos nemo id, labore assumenda velit quos porro quae sit recusandae sequi eum quod iure ullam expedita error, excepturi nihil provident ipsam!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum deserunt ab fugiat ut eum nihil non totam nemo iste sit optio, possimus explicabo officiis beatae corrupti recusandae veniam in odit.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis iure et, eum, aliquam blanditiis similique deserunt magni culpa nam quam id numquam sint provident. Voluptatem, impedit quas. Repellat, modi tempore.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis iure et, eum, aliquam blanditiis similique deserunt magni culpa nam quam id numquam sint provident. Voluptatem, impedit quas. Repellat, modi tempore.</p>
        <div id="contact">
          <%= link_to "Contact", "mailto:simonlacote@hotmail.fr", class: "btn btn-warning" %> 
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="bg">

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wallpaperaccess.com/full/3165466.jpg);">
  <div class="container">
    <h1>Copeaux Ludiks</h1>
    <p>Wood from the hood</p>
     <%= link_to presentation_path do%>
    <button type="button" class="btn btn-outline-warning">Presentation</button>
    <% end %>
  </div>
</div>


<div class="cards">

 <%= link_to ateliers_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2018/04/07/node_353848/39330516/public/2018/04/07/B9715318602Z.1_20180407192223_000%2BG0CB22QDD.1-0.jpg?itok=E3x0Y8W31523178856)">
      ATELIERS
    </div>
 <% end %>

  <%= link_to woodart_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2018/03/15/node_336103/39230399/public/2018/03/15/B9715059511Z.1_20180315181256_000%2BGTCAT0O7Q.1-0.jpg?itok=s2N6fitl1521197285)">
      WOOD ART
    </div>
  <% end %>

  <%= link_to meubles_path do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://capitolwords.org/wp-content/uploads/2020/04/Woodworking-Books.jpg)">
      MEUBLES SUR MESURE
    </div>
  <% end %>
  
</div>

</div>

app/views/pages/meubles.html.erb
<div class="bg">

  <div class="footer">
    <div class="footer-links">
    </div>
  </div>

  <div class="card-trip mx-auto">
    <img src="https://www.economist.com/sites/default/files/images/2017/09/articles/main/20170930_bkp504.jpg" />
    <div class="card-trip-infos">
      <div>
        <h2>Meubles</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates ullam quasi voluptatum at, eligendi vitae ratione asperiores quo, possimus, enim quibusdam. Eligendi hic quae laborum totam molestiae. Voluptate, quis facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos nemo id, labore assumenda velit quos porro quae sit recusandae sequi eum quod iure ullam expedita error, excepturi nihil provident ipsam!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum deserunt ab fugiat ut eum nihil non totam nemo iste sit optio, possimus explicabo officiis beatae corrupti recusandae veniam in odit.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis iure et, eum, aliquam blanditiis similique deserunt magni culpa nam quam id numquam sint provident. Voluptatem, impedit quas. Repellat, modi tempore.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis iure et, eum, aliquam blanditiis similique deserunt magni culpa nam quam id numquam sint provident. Voluptatem, impedit quas. Repellat, modi tempore.</p>
        <div id="contact">
          <%= link_to "Contact", "mailto:simonlacote@hotmail.fr", class: "btn btn-warning" %> 
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/pages/woodart.html.erb
<div class="bg">

  <div class="footer">
    <div class="footer-links">
    </div>
  </div>

  <div class="card-trip mx-auto">

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">

        <div class="carousel-item active">
        <img src="https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2018/03/15/node_336103/39230399/public/2018/03/15/B9715059511Z.1_20180315181256_000%2BGTCAT0O7Q.1-0.jpg?itok=s2N6fitl1521197285" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
        <img src="https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_in_line/2018/03/14/node_335354/39226804/public/2018/03/14/B9715062664Z.1_20180314193038_000%2BGTCAT20ID.1-0.jpg?itok=AmZFylHp1521052247" class="d-block w-50 mx-auto" alt="...">
        </div>
        <div class="carousel-item">
        <img src="https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2019/04/06/node_564531/40235381/public/2019/04/06/B9719168932Z.1_20190406180501_000%2BG2HDBAOBI.1-0.jpg?itok=cFWJjeIU1554566717" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
        <img src="https://lvdneng.rosselcdn.net/sites/default/files/dpistyles_v2/ena_16_9_extra_big/2019/10/02/node_645973/40841790/public/2019/10/02/B9721111694Z.1_20191002171527_000%2BGRIEJOQBH.2-0.jpg?itok=Xapcrfw-1570522144" class="d-block w-100" alt="...">
        </div>

    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>

    <div class="card-trip-infos">
      <div>
        <h2>Wood Art</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptates ullam quasi voluptatum at, eligendi vitae ratione asperiores quo, possimus, enim quibusdam. Eligendi hic quae laborum totam molestiae. Voluptate, quis facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos nemo id, labore assumenda velit quos porro quae sit recusandae sequi eum quod iure ullam expedita error, excepturi nihil provident ipsam!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rerum deserunt ab fugiat ut eum nihil non totam nemo iste sit optio, possimus explicabo officiis beatae corrupti recusandae veniam in odit.</p>
        <div id="contact">
          <%= link_to "Shop", src="https://www.artmajeur.com/sebastien-riga", class: "btn btn-warning" %> 
        </div>
      </div>  
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>